spring:
  application:
    name: back-end
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    database: default
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      base-path: /

thirdPartyApi:
  energyDataApi:
    baseUrl: ${ENERGY_DATA_API_BASE_URL:http://localhost:8888}
    apiKey: ${ENERGY_DATA_API_KEY:test-api-key}
  weatherApi:
    baseUrl: ${WEATHER_API_BASE_URL:https://api.openweathermap.org}
    apiKey: ${WEATHER_API_KEY}

jobs:
  schedule:
    enabled: false
    weatherData: ${WEATHER_DATA_JOB_CRON:0 0 */1 * * *}
    consumptionData: ${CONSUMPTION_DATA_JOB_CRON:0 0 */1 * * *}
    productionData: ${PRODUCTION_DATA_JOB_CRON:0 */5 * * * *}
